import type { Product, Review } from "@/lib/types";

const unsplash = (photo: string, width = 1200) =>
  `https://images.unsplash.com/${photo}?auto=format&fit=crop&w=${width}&q=85`;

export const demoProducts: Product[] = [
  {
    id: "green-goddess-bowl",
    slug: "green-goddess-bowl",
    name: "Green Goddess Bowl",
    subtitle: "The one that makes greens feel like a treat.",
    description:
      "A big, bright bowl of the good stuff: buttery avocado, crispy chickpeas, shaved cucumber, pickled shallot, and a very generous pour of our lemon-herb green goddess dressing. Tossed to order, never sitting around.",
    category: "Bowls",
    price: 1590,
    compareAtPrice: 1750,
    images: [
      unsplash("photo-1512621776951-a57141f2eefd"),
      unsplash("photo-1540189549336-e6e99c3679fe"),
      unsplash("photo-1490645935967-10de6ba17061"),
    ],
    badge: "Fan favorite",
    rating: 4.9,
    reviewCount: 184,
    prepTime: 18,
    isBestseller: true,
    dietary: ["Vegetarian", "Gluten free"],
    ingredients: ["Avocado", "Crispy chickpeas", "Baby kale", "Cucumber", "Green goddess dressing"],
  },
  {
    id: "miso-glazed-salmon",
    slug: "miso-glazed-salmon",
    name: "Miso-glazed Salmon",
    subtitle: "Sweet, savory, gone in five minutes.",
    description:
      "Line-caught salmon gets a slow brush of white miso, local honey, and a little ginger, then a quick kiss from the flame. Set on sesame rice with crunchy greens and a bright little citrus ponzu.",
    category: "Bowls",
    price: 1890,
    compareAtPrice: null,
    images: [
      unsplash("photo-1467003909585-2f8a72700288"),
      unsplash("photo-1519708227418-c8fd9a32b7a2"),
      unsplash("photo-1498654896293-37aacf113fd9"),
    ],
    badge: "Kitchen pick",
    rating: 4.9,
    reviewCount: 127,
    prepTime: 24,
    isBestseller: true,
    dietary: ["Dairy free"],
    ingredients: ["Line-caught salmon", "White miso", "Sesame rice", "Ginger", "Citrus ponzu"],
  },
  {
    id: "crunchy-chickpea-bowl",
    slug: "crunchy-chickpea-bowl",
    name: "Crunchy Chickpea Bowl",
    subtitle: "Big crunch. Bigger feel-good energy.",
    description:
      "Warm turmeric chickpeas, cool crunchy cabbage, fluffy herbed quinoa, and a swoosh of smoky tahini. Finished with pomegranate, mint, and all the textures your lunch break deserves.",
    category: "Bowls",
    price: 1450,
    compareAtPrice: null,
    images: [
      unsplash("photo-1540189549336-e6e99c3679fe"),
      unsplash("photo-1512621776951-a57141f2eefd"),
      unsplash("photo-1511690743698-d9d85f2fbf38"),
    ],
    badge: "Plant-powered",
    rating: 4.8,
    reviewCount: 92,
    prepTime: 16,
    isBestseller: false,
    dietary: ["Vegan", "Gluten free"],
    ingredients: ["Roasted chickpeas", "Herbed quinoa", "Red cabbage", "Pomegranate", "Smoky tahini"],
  },
  {
    id: "crispy-chicken-sandwich",
    slug: "crispy-chicken-sandwich",
    name: "Crispy Chicken Sando",
    subtitle: "A proper little stack of happiness.",
    description:
      "Buttermilk-brined chicken, fried until ridiculously crisp, tucked into a pillowy potato bun with tangy slaw, dill pickles, and our house pepper mayo. Handheld, not to be shared.",
    category: "Handhelds",
    price: 1650,
    compareAtPrice: 1800,
    images: [
      unsplash("photo-1606755962773-d324e0a13086"),
      unsplash("photo-1553909489-cd47e0ef937f"),
      unsplash("photo-1555939594-58d7cb561ad1"),
    ],
    badge: "Most loved",
    rating: 4.9,
    reviewCount: 211,
    prepTime: 20,
    isBestseller: true,
    dietary: [],
    ingredients: ["Free-range chicken", "Potato bun", "Dill pickles", "Cabbage slaw", "Pepper mayo"],
  },
  {
    id: "hot-honey-halloumi-wrap",
    slug: "hot-honey-halloumi-wrap",
    name: "Hot Honey Halloumi Wrap",
    subtitle: "A little sweet, a little heat, a lot to love.",
    description:
      "Golden, squeaky halloumi meets sticky hot honey in a warm flatbread with crunchy little gem, tomato, and cool minty yogurt. The kind of sweet-heat situation you think about tomorrow.",
    category: "Handhelds",
    price: 1490,
    compareAtPrice: null,
    images: [
      unsplash("photo-1525351484163-7529414344d8"),
      unsplash("photo-1553909489-cd47e0ef937f"),
      unsplash("photo-1540420773420-3366772f4999"),
    ],
    badge: "A little spicy",
    rating: 4.8,
    reviewCount: 86,
    prepTime: 16,
    isBestseller: false,
    dietary: ["Vegetarian"],
    ingredients: ["Grilled halloumi", "Hot honey", "Warm flatbread", "Little gem", "Mint yogurt"],
  },
  {
    id: "roast-chicken-plate",
    slug: "roast-chicken-plate",
    name: "Sunday Roast Chicken",
    subtitle: "Sunday-table comfort, any day you want it.",
    description:
      "Half a lemony, rosemary-roasted chicken with golden potatoes, silky pan gravy, and a pile of buttered greens. Slow Sunday flavor, brought right to your weeknight.",
    category: "Mains",
    price: 2150,
    compareAtPrice: null,
    images: [
      unsplash("photo-1532550907401-a500c9a57435"),
      unsplash("photo-1598103442097-8b74394b95c6"),
      unsplash("photo-1600891964599-f61ba0e24092"),
    ],
    badge: "Sunday energy",
    rating: 4.9,
    reviewCount: 143,
    prepTime: 28,
    isBestseller: true,
    dietary: ["Gluten free"],
    ingredients: ["Free-range chicken", "Rosemary", "Baby potatoes", "Seasonal greens", "Pan gravy"],
  },
  {
    id: "truffle-parmesan-fries",
    slug: "truffle-parmesan-fries",
    name: "Truffle Parm Fries",
    subtitle: "Your plus-one's new favorite side.",
    description:
      "Skin-on potatoes, double-cooked for that proper crunch, tossed with aged parmesan, black truffle, and the tiniest pinch of flaky sea salt. Best eaten while they're still warm.",
    category: "Sides",
    price: 750,
    compareAtPrice: null,
    images: [
      unsplash("photo-1573080496219-bb080dd4f877"),
      unsplash("photo-1630384060421-cb20d0e0649d"),
      unsplash("photo-1518013431117-eb1465fa5752"),
    ],
    badge: null,
    rating: 4.7,
    reviewCount: 64,
    prepTime: 12,
    isBestseller: false,
    dietary: ["Vegetarian", "Gluten free"],
    ingredients: ["Skin-on potatoes", "Aged parmesan", "Black truffle", "Flaky sea salt"],
  },
  {
    id: "brown-butter-cookies",
    slug: "brown-butter-cookies",
    name: "Brown Butter Cookies",
    subtitle: "Two gooey, golden little mood-lifters.",
    description:
      "Our still-warm brown butter cookies have crisp, caramelized edges, soft middles, and big puddles of dark chocolate. A tiny sprinkle of flaky salt. Two to a box, one for now and one for later.",
    category: "Sweets",
    price: 650,
    compareAtPrice: null,
    images: [
      unsplash("photo-1499636136210-6f4ee915583e"),
      unsplash("photo-1558961363-fa8fdf82db35"),
      unsplash("photo-1498049794561-7780e7231661"),
    ],
    badge: "Baked today",
    rating: 4.9,
    reviewCount: 203,
    prepTime: 5,
    isBestseller: true,
    dietary: ["Vegetarian"],
    ingredients: ["Cultured butter", "Dark chocolate", "Brown sugar", "Free-range eggs", "Flaky salt"],
  },
  {
    id: "lemon-olive-oil-cake",
    slug: "lemon-olive-oil-cake",
    name: "Lemon Olive Oil Cake",
    subtitle: "Sunshine, with a little powdered sugar.",
    description:
      "Tender, fragrant cake made with early-harvest olive oil, fresh lemon zest, and a little love. Finished with a soft cloud of crème fraîche and whatever fruit looks best this morning.",
    category: "Sweets",
    price: 790,
    compareAtPrice: null,
    images: [
      unsplash("photo-1578985545062-69928b1d9587"),
      unsplash("photo-1464305795204-6f5bbfc7fb81"),
      unsplash("photo-1488477181946-6428a0291777"),
    ],
    badge: "Small batch",
    rating: 4.8,
    reviewCount: 58,
    prepTime: 6,
    isBestseller: false,
    dietary: ["Vegetarian"],
    ingredients: ["Extra-virgin olive oil", "Fresh lemon", "Almond flour", "Crème fraîche", "Seasonal fruit"],
  },
  {
    id: "strawberry-basil-spritz",
    slug: "strawberry-basil-spritz",
    name: "Strawberry Basil Spritz",
    subtitle: "A little afternoon sunshine in a glass.",
    description:
      "Ripe local strawberries, muddled garden basil, sparkling water, and a squeeze of lime. Bright, bubbly, zero-proof, and packed with the feeling that maybe you should take a longer lunch.",
    category: "Sips",
    price: 690,
    compareAtPrice: null,
    images: [
      unsplash("photo-1513558161293-cdaf765edfd7"),
      unsplash("photo-1497534446932-c925b458314e"),
      unsplash("photo-1544145945-f90425340c7e"),
    ],
    badge: "Zero-proof",
    rating: 4.8,
    reviewCount: 77,
    prepTime: 4,
    isBestseller: false,
    dietary: ["Vegan", "Gluten free"],
    ingredients: ["Local strawberries", "Garden basil", "Sparkling water", "Fresh lime"],
  },
];

export const demoReviews: Review[] = [
  { id: "review-green-1", productId: "green-goddess-bowl", customerName: "Lena M.", neighborhood: "Silver Lake", rating: 5, title: "My new lunch ritual", body: "So fresh, dressing on the side exactly like I asked, and the crispy chickpeas are dangerously good. Arrived before my meeting ended.", createdAt: new Date("2025-02-04T12:10:00Z") },
  { id: "review-green-2", productId: "green-goddess-bowl", customerName: "Chris R.", neighborhood: "Echo Park", rating: 5, title: "The greens are actually exciting", body: "You can taste how fresh everything is. Big enough to keep me full all afternoon without the post-lunch slump.", createdAt: new Date("2025-01-27T18:35:00Z") },
  { id: "review-salmon-1", productId: "miso-glazed-salmon", customerName: "Priya K.", neighborhood: "Los Feliz", rating: 5, title: "Restaurant-level lunch", body: "That miso glaze! The salmon was flaky and the ponzu kept everything so bright. Already added this to my weekly rotation.", createdAt: new Date("2025-02-02T19:04:00Z") },
  { id: "review-salmon-2", productId: "miso-glazed-salmon", customerName: "Evan S.", neighborhood: "Silver Lake", rating: 5, title: "Perfectly cooked", body: "Warm, delicious, and packed like someone actually cared about the ride over. This is how delivery should be.", createdAt: new Date("2025-01-24T13:18:00Z") },
  { id: "review-chickpea-1", productId: "crunchy-chickpea-bowl", customerName: "Amara D.", neighborhood: "Atwater Village", rating: 5, title: "Plant-based and filling", body: "I usually need a snack an hour after a salad. Not this bowl. The tahini is smoky and the pomegranate is a lovely surprise.", createdAt: new Date("2025-02-01T12:42:00Z") },
  { id: "review-chickpea-2", productId: "crunchy-chickpea-bowl", customerName: "Jordan P.", neighborhood: "Echo Park", rating: 4, title: "A really good lunch", body: "Great mix of textures and the quinoa was still warm. I'd love to see this on the menu forever.", createdAt: new Date("2025-01-19T11:55:00Z") },
  { id: "review-sando-1", productId: "crispy-chicken-sandwich", customerName: "Mia T.", neighborhood: "Silver Lake", rating: 5, title: "The crunch is unreal", body: "Pickles, slaw, chicken, bun — every bite is perfect. It showed up hot and crisp, which honestly feels like magic.", createdAt: new Date("2025-02-03T20:22:00Z") },
  { id: "review-sando-2", productId: "crispy-chicken-sandwich", customerName: "Noah B.", neighborhood: "Los Feliz", rating: 5, title: "Order the fries too", body: "The pepper mayo is the secret. Easily the best chicken sandwich I've had delivered around here.", createdAt: new Date("2025-01-25T17:47:00Z") },
  { id: "review-halloumi-1", productId: "hot-honey-halloumi-wrap", customerName: "Zoe L.", neighborhood: "Atwater Village", rating: 5, title: "Sweet heat perfection", body: "The halloumi was golden and the mint yogurt balances the honey perfectly. Super satisfying without feeling too heavy.", createdAt: new Date("2025-01-30T12:20:00Z") },
  { id: "review-halloumi-2", productId: "hot-honey-halloumi-wrap", customerName: "Sam F.", neighborhood: "Echo Park", rating: 4, title: "A fun little lunch", body: "A really generous wrap with lovely fresh greens. The honey has just the right kick.", createdAt: new Date("2025-01-15T13:05:00Z") },
  { id: "review-roast-1", productId: "roast-chicken-plate", customerName: "Ruby A.", neighborhood: "Silver Lake", rating: 5, title: "Comfort food, upgraded", body: "The potatoes and gravy transported me to Sunday dinner at my mum's, but better. Portions are super generous.", createdAt: new Date("2025-02-02T18:41:00Z") },
  { id: "review-roast-2", productId: "roast-chicken-plate", customerName: "Theo C.", neighborhood: "Los Feliz", rating: 5, title: "Weeknight hero", body: "Perfectly juicy chicken and beautifully seasoned greens. It's going straight onto our family favourites list.", createdAt: new Date("2025-01-22T19:13:00Z") },
  { id: "review-fries-1", productId: "truffle-parmesan-fries", customerName: "Max J.", neighborhood: "Echo Park", rating: 5, title: "The side that steals the show", body: "Crispy all the way home. We may have accidentally made these the main course.", createdAt: new Date("2025-01-29T20:31:00Z") },
  { id: "review-fries-2", productId: "truffle-parmesan-fries", customerName: "Elle W.", neighborhood: "Silver Lake", rating: 4, title: "Very snackable", body: "Lovely parmesan and good truffle balance — not overpowering like some places.", createdAt: new Date("2025-01-10T16:29:00Z") },
  { id: "review-cookie-1", productId: "brown-butter-cookies", customerName: "Jules N.", neighborhood: "Los Feliz", rating: 5, title: "The best two dollars I spent today", body: "Ordered these for the table and everyone asked where they came from. Gooey middle, salty edge, perfect.", createdAt: new Date("2025-02-03T14:36:00Z") },
  { id: "review-cookie-2", productId: "brown-butter-cookies", customerName: "Ivy G.", neighborhood: "Atwater Village", rating: 5, title: "Still warm!", body: "I will be ordering these every single time. They made it to our door still soft in the middle.", createdAt: new Date("2025-01-18T21:06:00Z") },
  { id: "review-cake-1", productId: "lemon-olive-oil-cake", customerName: "Nina V.", neighborhood: "Silver Lake", rating: 5, title: "Just the right amount of lemon", body: "Light, lemony, not too sweet. The fruit on top made it feel like a tiny celebration.", createdAt: new Date("2025-01-26T15:02:00Z") },
  { id: "review-cake-2", productId: "lemon-olive-oil-cake", customerName: "Ari E.", neighborhood: "Echo Park", rating: 4, title: "Lovely after-dinner treat", body: "You can taste the good olive oil. Shared one slice, immediately wished we had ordered another.", createdAt: new Date("2025-01-09T20:43:00Z") },
  { id: "review-spritz-1", productId: "strawberry-basil-spritz", customerName: "Dani Q.", neighborhood: "Atwater Village", rating: 5, title: "My new afternoon pick-me-up", body: "Fresh and not too sweet, and it actually tastes like strawberries. Came ice cold, too.", createdAt: new Date("2025-02-01T15:45:00Z") },
  { id: "review-spritz-2", productId: "strawberry-basil-spritz", customerName: "Kai H.", neighborhood: "Los Feliz", rating: 4, title: "So refreshing", body: "The basil makes this. Absolutely perfect with the halloumi wrap.", createdAt: new Date("2025-01-12T16:18:00Z") },
];
